# real-estate-service/docker-compose.yml
services:
  real-estate-service:
    container_name: real-estate-service
    build: .
    image: real-estate-service:latest
    env_file:
      - .env.staging
    environment:
      NODE_ENV: ${NODE_ENV:-staging}
      PORT: ${PORT:-3003}
      APP_RESOURCE_NAME: real-estate
      # for√ßa a URL correta dentro da rede Docker
      JWT_SERVICE_URL: https://auth-service:3000/v1
    ports:
      - "${PORT:-3003}:${PORT:-3003}"
    networks:
      smart-net:
        aliases: [real-estate-service]
    healthcheck:
      test: ["CMD-SHELL","curl -ks https://localhost:${PORT:-3003}/health || curl -s http://localhost:${PORT:-3003}/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10
    volumes:
      - ./certs:/app/certs:ro
      - ./logs:/app/logs

networks:
  smart-net:
    external: true
